#store the file in your working directory.
#and then read into a data frame.

brexit_data <- read.csv("data_brexit_referendum.csv")
head(brexit_data)

#what data type is this file?
class(brexit_data)

#Lets look at the struture of the file
str(brexit_data)

#Dealing with missing value

#In the orginial data has missing value represented by the number -1
#We need to search for this and replace them.

#check the -1 values in the column leave
sum(brexit_data$Leave[brexit_data$Leave == -1])

#replace them with NA value.
brexit_data$Leave[brexit_data$Leave == -1] <- NA

#Check the values are replaced.
sum(brexit_data$Leave[brexit_data$Leave == -1])

#view the records with NA.
na_values <- brexit_data[!complete.cases(brexit_data),]
na_values

#count of rows with NA value.
nrow(na_values)

#To check the number of missing values from orginal data
#Mice package is used.

install.packages("mice")
library("mice")
# 15 records have missing NI address
# 10 have missing type.
md.pattern(brexit_data)

#267 rows out of 1070 has the null values.
nrow(brexit_data)

library(VIM)
#Looks like the missing values are all in this 1 column.
#for "Leave". We're not going to use it for now.
#so we'll leave it as it is.

missing_values <- aggr(brexit_data, prop = FALSE, numbers = TRUE)

#Describing the brexit data.

#Lets look at the proportion of voters who
#are in favour of leaving the E.U.
#I'm creating a new variable to store this information in.
#The focus of this dataset is brexit voters and their various attributes.

brexit_data$proportion <- brexit_data$Leave / brexit_data$NVotes
brexit_data$proportion

#store remain or leave in the Vote variable.
brexit_data$Vote[brexit_data$proportion <=0.5] <- "Remain"
brexit_data$Vote[brexit_data$proportion > 0.5] <- "Leave"
brexit_data$Vote

attach(brexit_data)
#Note that we still need to refer to the full path to the variable for
#part of the statement.

# Need to covert to character from factor before we can convert the variable.

brexit_data$RegionName <- as.character(RegionName)
str(brexit_data)

brexit_data$RegionName[brexit_data$RegionName == "London"] <- "L"
brexit_data$RegionName[brexit_data$RegionName == "North West"] <- "NW"
brexit_data$RegionName[brexit_data$RegionName == "North East"] <- "NE"
brexit_data$RegionName[brexit_data$RegionName == "South West"] <- "SW"
brexit_data$RegionName[brexit_data$RegionName == "South East"] <- "SE"
brexit_data$RegionName[brexit_data$RegionName == "East Midlands"] <- "EM"
brexit_data$RegionName[brexit_data$RegionName == "West Midlands"] <- "WM"
brexit_data$RegionName[brexit_data$RegionName == "East of England"] <- "EE"
brexit_data$RegionName[brexit_data$RegionName == "Yorkshire and The Humber"] <- "Y"

# Now we have a new variable of interset called proportion.
# and we will now focus on this variable.

# lets view the summary of the data.
summary(brexit_data)

# we're not able to directly reference this data because some is non-numeric.
# and does not contain what we want to view such as minimum, first quartile, median, mean, third quartile
# but we can use sapply() and check whelther each data variable is a numeric varaible or not.
# eg to check whether proportion is a numeric value or not.

# using sapply() identifying the numeric and non-numeric variables.
numeric_variable_list <- sapply(brexit_data, is.numeric)
numeric_variable_list

# we can use this logic to create a subset of the data with only
# numeric values.
numerical_data <- brexit_data[numeric_variable_list]
colnames(numerical_data)

#Remove the ID field as it has no meaning.
numeric_variable_list["ID"] <- FALSE

#Then remove this again from the main file_data dataset.
numerical_data <- brexit_data[numeric_variable_list]
colnames(numerical_data)

# We can use a lapply() function to return a named list
# where each list member has a corresponding name
lapply(numerical_data, summary)

?cbind()
# cbind() combines objects by rows and columns.
# so we can use this function to create a dataset.
# of the lapply() output.

# do.call() function will allow us to.
# apply the cbind() to each element generated by lapply()
?do.call
numerical_summaryb <- do.call(cbind,lapply(numerical_data, summary))

# Error message shows additional ine - caused by NA's
# We could drop NA's but that will only fix this one issue
# Instead we need to go back to the source and drop NA's

brexit_data <- brexit_data[complete.cases(brexit_data),]
numerical_data <- brexit_data[numeric_variable_list]
numerical_summary <- do.call(cbind, lapply(numerical_data, summary))
numerical_summary

# we can do a swap with summary values as columns and variables as rows
# then we use rbind()
alt_numerical_summary <- do.call(rbind, lapply(numerical_data, summary))
alt_numerical_summary

# Now we can apply some computation
# such as finding range between wards with the least and most proportions of votes in
# favour of leaving (0.6681), which may be useful to interpret the big difference
# among the types of wards we may find in the UK. If we want to know which wards are being used to 
# get to this result, we can search for the wards with the least and most proportion of votes

# we can use this data to show specific values such as 
# the max proportion value - max percent of those who voted to leave
# prop = leave / no values in ward
numerical_summary["Max.", "proportion"]
numerical_summary                                 

# And the min proportion value can show us
numerical_summary["Min.","proportion"]

numerical_summary["Max.", "proportion"] - numerical_summary["Min.","proportion"]

# Lets look at values of those who wanted to leave or stay
display_variables <- c("NoQuals","proportion","AdultMeanAge","L4Quals_plus","RegionName")

# Values show that those with mean age of 46.9 and 29% no qualifications
# and 27.3 with level 4 quals (degree and above) voted to leave
brexit_data[which.max(brexit_data$proportion), display_variables]

#Those who wanted to stay were younger with better qualifications
brexit_data[which.min(brexit_data$proportion), display_variables]

table(brexit_data$RegionName)

?prop.table
#table value expressed as fractions
prop.table(table(brexit_data$RegionName))

barplot(height = prop.table(table(brexit_data$RegionName)),
        main = "Vote proportion by Region",
        ylab = "Frequency",
        xlab = "Region",
        col = "white")

# chart where each point represents a ward.
# observation, and it shows the proportion of Leave votes for each ward, arranged in
# vertical lines corresponding to RegionName and coloured by the proportion of white
# population for each ward. As you can see,we have another interesting finding; it seems that
# the more diversified a ward's population is (seen in the darker points), the more likely its is
# for the ward to vote in favor of remaining in the EU (a lower proportion value).



